### ISSUE TITLE
Problems in node 9 and crypto

### ISSUE THREAD

**Issue by LordSuricato** [sehrope/node-rand-token#9]
`TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
at randomBytes (internal/crypto/random.js:44:11)
`
It is explained here
[https://github.com/diegohaz/rest/issues/133](url)

**Comment by sehrope** [comment]
This is due a breaking change (for undocumented behavior) in NodeJS v9. See here for more details on the cause: https://github.com/nodejs/node/issues/16778

This is fixed in newer version of rand-token by commit 763df115c3920f8a4286960249f3e09b3bd85d73. Upgrade to the latest version (v0.4.0 as of writing this) of rand-token and it'll be resolved.

**Comment by martinbedouret** [comment]
I have updated to v0.4.0 and the same issue still there. I'm on ubuntu 17 node 9.3

**Comment by sehrope** [comment]
@martinbedouret Clear your dependencies (via `rm -rf node_modules`) and try again. You probably have the older version cached in node_modules. If that doesn't fix it then submit a separate issue with steps to reproduce.

```
$ node --version
v9.3.0

$ npm install rand-token
+ rand-token@0.4.0
added 1 package in 0.58s

$ node -p "require('rand-token').uid(16)"
Fy28UXPDr2vnL0Wz
```
